### ISSUE TITLE
A new release should be done.

### ISSUE THREAD

**Issue by SerhiiD** [AileenMolot/HTML#8]
It's time to do a new release. Please do following steps:

- [x] 1. merge all pull requests;
- [x] 2. merge **dev** to **master**;
- [x] 3. merge **master** to **dev**;
- [x] 4. add a TAG on the master branch with product version in it. For example, **release 1.0.0**.

Good luck!

**Comment by AileenMolot** [comment]
Done :1st_place_medal:
